#################################################################
## Home Assistant - Core Configuration
#################################################################


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

config:

# Track the sun
sun:

# Checks for available updates
updater:
  reporting: no

#################################################################
## Components
#################################################################

logger:
  default: info

map:

# Enables support for tracking state changes over time.
history:

# Stream Componant
stream:

# Enables the frontend
frontend:
  javascript_version: latest

# Lovelace
#lovelace:
#  mode: yaml


# enable HACS custom components
hacs:
  token: !secret HACS_token

# Text to speech
tts:
  - platform: google_translate

######## INCLUDES ########
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include camera.yaml
http: !include http.yaml